name: Trigger Workflow on Discussion

on:
  discussion:
    types:
      - created

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract discussion information
        id: prompt
        run: |
          echo "DISCUSSION_BODY=$(echo '${{ toJson(github.event) }}' | jq -r '.discussion.body')" >> $GITHUB_ENV

  use_gpt:
    needs: triage
    runs-on: ubuntu-latest
    steps:
      - name: Get discussion info from previous step
        id: discussion_info
        run: |
          echo "DISCUSSION_BODY=${{ needs.triage.outputs.DISCUSSION_BODY }}" >> $GITHUB_ENV

      - name: Print Discussion Body
        run: |
          echo "Using Discussion Body: $DISCUSSION_BODY"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install Dependencies
        run: npm install
        working-directory: ./DocumentChatgpt

      - name: Run ChatGPT Script
        run: node chat.js
        working-directory: ./DocumentChatgpt
        env:
          OPENAI_API_KEY: ${{ secrets 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  }}
          DISCUSSION_BODY: ${{ needs.triage.outputs.DISCUSSION_BODY }}
