name: Trigger Workflow on Discussion
on:
  discussion:
    types:
      - created

jobs:
  triage:
    if: >-
      github.event.discussion.category.name == 'General'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract discussion information
        id: prompt
        run: |
          echo "title=${{ github.event.discussion.title }}" >> $GITHUB_ENV
          echo "body=${{ github.event.discussion.body }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  use_gpt:
    needs: triage
    runs-on: ubuntu-latest
    steps:
      - name: Get discussion info from previous step
        id: discussion_info
        run: |
          echo "title=${{ needs.triage.outputs.title }}" >> $GITHUB_ENV
          echo "body=${{ needs.triage.outputs.body }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display discussion title
        run: |
          echo "Discussion Title: ${{ needs.triage.outputs.title }}"
        working-directory: ${{ env.PWD }}
      - name: Display discussion body
        run: |
          echo "Discussion Body: ${{ needs.triage.outputs.body }}"
        working-directory: ${{ env.PWD }}
      - name: Use ChatGPT API
        run: |
           node main.js # Make sure to use the correct filename here
        working-directory: ${{ env.PWD }}
