name: Trigger ChatGPT on Discussion

on:
  discussion:
    types:
      - created

jobs:
  run_chatgpt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Discussion Body
        run: echo "DISCUSSION_BODY=${{ toJson(github.event.discussion.body) }}" >> $GITHUB_ENV

      - name: Print Current Directory
        run: pwd

      - name: List Files in Directory
        run: ls -la

      - name: Run ChatGPT Script
        run: node chat.js
        working-directory: ./DocumentChatgpt
