name: Trigger Workflow on Discussion

on:
  discussion:
    types:
      - created

jobs:
  triage:
    if: >-
      github.event.discussion.category.name == 'General'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract discussion information
        id: prompt
        run: |
          echo "DISCUSSION_BODY=${{ github.event.discussion.body }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  use_gpt:
    needs: triage
    runs-on: ubuntu-latest
    steps:
      - name: Get discussion body from previous step
        id: discussion_info
        run: |
          echo "DISCUSSION_BODY=${{ needs.triage.outputs.DISCUSSION_BODY }}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display discussion body
        run: |
          echo "Discussion Body: ${{ needs.triage.outputs.DISCUSSION_BODY }}"
      - name: Run ChatGPT script
        run: |
           node main.js
