name: Trigger Workflow on Discussion

on:
  discussion:
    types:
      - created

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

  triage:
    if: >-
      github.event.discussion.category.name == 'General'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract discussion information
        id: prompt
        run: |
          echo "body=$(echo '${{ toJson(github.event) }}' | jq -r '.discussion.body')" >> $GITHUB_ENV

  use_gpt:
    needs: triage
    runs-on: windows-latest
    steps:
      - name: Get discussion info from previous step
        id: discussion_info
        run: |
          echo "body=${{ needs.triage.outputs.body }}" >> $GITHUB_ENV

      - name: Use ChatGPT API
        working-directory: ./DocumentChatgpt
        run: |
          $env:DISCUSSION_BODY="${{ needs.triage.outputs.body }}"
          Write-Host "Using Discussion Body: $env:DISCUSSION_BODY"
          Write-Host "Running ChatGPT script..."
          node .\chat.js
