on:
  issues:
    types: [opened, edited]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: kiran-godse/labeling-by-gpt@main
        with:
          openai-api-key: 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
          github-token: ${{ secrets.GITHUB_TOKEN }}
